<h1 style="font-size:60px; 
           color:orangered;
           text-align:center;
           border-bottom:3px solid orangered">
    PROYECTO CIENCIA DE DATOS</h1>

# Tabla de contenido

- [__Proyecto final 0__](#ind00)
- [__Objetivo 1__](#ind01)
- [__Contexto analitico 2__](#ind02)
- [__Data acquisition 3__](#ind03)
- [__Exploratory data analysis (EDA) 4__](#ind04)
- [__Data wrangling 5__](#ind05)
- [__Feature selection 6__](#ind06)
- [__Machine learning 7__](#ind07)
- [__Conclusion 8__](#ind08)

---

# 0. Proyecto final

_¿Cual es la probabilidad que tengo de ganar o perder una partida de un videojuego?_ Esta, es la pregunta principal que vamos a investigar a lo largo de este proyecto. El juego Leagoe of Legend consta de dos equipos 5 vs 5 que el objetivo de cada equipo es destruir la base enemiga. Para esto, el mapa se compone por tres lineas en las cuales iran los jugadores. Existen multiples personajes para jugar en cada partida que reciben el nombre de campeones. Estos últimos se diferencias por categorias, role, funcion y habilidades. Dependiendo de cada campeon, tiene un impacto distinto en la partida. Entonces... ¿Como vamos a realizar este proyecto? Para el mismo, generaremos una base de datos en base a las Apis que nos provee el mismo videojuego. Gracias a ellas seremos capaces de observar una partida en curso y ver los jugadores de la misma. Una vez que tengamos esa misma, emplaremos multiples funciones para obtener el historial de las ultimas 10 partidas de cada uno de los jugadores, en base a estas observaremos el desempeno de ellos y analizaremos a los mismos, una vez que tengamos esto podremos analizar las probabilidad de ganar la partida que tiene cada uno de los equipos.

# 1. Objetivo

_¿Cual es la probabilidad de ganar o perder?_ Como  vimos en el apartado anterior este es el objetivo de este proyecto. Se quiere investigar las mukltiples variables que disponemos dentro de las APIs del League Of Legends, de ahora en adelante lo llamaremos lol, para asi de esta forma encontrar la coneccion que tenemops entre ellas a lo largo del historial del jugador. En base al historial historico de un jugador, analizaremos todas sus partidas para comenzar a deducir patrones, aspectos que se compartan. Algunos de ellos pueden ser con quien juega acompañado por ejemplo, mientras que otros pueden ser conceptos mas tecnicos dentro del mismo juego como el nivel de farmeo (hace referencia a la cantidad de subditos que elimino) entre muchos otros. 

Para la resolucion de esta problematica existen alguns preguntas que pueden comenzar a guiar el proyecto en un rumbo. Debajo se dejara un listado con las mismas:

- ¿Cuantas partidas jugo el jugador en los ultimos 5 años?¿Cuantas por año?
- ¿Cual es el KDA (kill, deaths, assistants) del mismo?¿Como fue evolucionando en cada año?
- ¿Cuales son los campeones que más usa?¿Como evoluciono con cada uno (KDA con el campeon)?
- ¿Cuales son los campeones con mayor nivel de maestria que posee?
- ¿Cual es el nivel de farmeo del jugador?
- ¿Cual es el nivel de vision del mapa del jugador?
- ¿En que linea se desempeño mejor?¿Que clase de campeon empleo para ello?

# 2. Contexto analitico

Para este proyecto analizaremos el historial de partidas junto a otras caracteristicas de cada un jugador. Para obtener estos datos implementaremos el uso directo de las APIs proporcionadas por Riot Games (desarrolladora del juego). Entre ellas nos podemos encontrar los siguientes links que estaremos usando.

__Developers home page__
- https://developer.riotgames.com/

__APIs de Riot Games__
- https://developer.riotgames.com/apis#league-v4

__APIs information__
- https://developer.riotgames.com/docs/portal#_overview

# 3. Data acquisition

## 3.1 Librerias

In [1]:
## Cargamos las librerias que seran nesarias
# Para trabajar los datos
import json
import requests
import pandas as pd
import numpy as np
from modules import utils as ut

# Para traer la api key
import os
from dotenv import load_dotenv

# Para eliminar los carteles warnings
import warnings as wn

In [2]:
# Importamos la api key
# Obtén la ruta absoluta del archivo .env
env_path = os.path.join(os.path.dirname('testing.ipynb'), 'conf', '.env')

# Carga las variables de entorno desde el archivo .env
load_dotenv(env_path)

# Accede a la variable de entorno
key_admin = os.getenv('key_admin')

## 3.2 Base de datos desde API

In [4]:
partida01 = pd.read_csv('data/live_matchs/partida01.csv', delimiter=';', index_col=0)
partida02 = pd.read_csv('data/live_matchs/partida02.csv', delimiter=';', index_col=0)
partida03 = pd.read_csv('data/live_matchs/partida03.csv', delimiter=';', index_col=0)
partida04 = pd.read_csv('data/live_matchs/partida04.csv', delimiter=';', index_col=0)

In [4]:
df_games = pd.read_csv('data/df_games.csv')

C:\Users\herne\AppData\Local\Temp\ipykernel_6716\3473350840.py:1: DtypeWarning: Columns (106) have mixed types. Specify dtype option on import or set low_memory=False.
  df_games = pd.read_csv('data/df_games.csv')

<h2 style="font-size:30px; 
           color:orangered;
           text-align:center;
           border-bottom:3px solid orangered">
    Controlamos que las partidas del historial tengan los mismos datos que las partidas en vivo</h2>

In [21]:
df_games

,index,assists,baronKills,bountyLevel,champExperience,champLevel,championId,championName,championTransform,consumablesPurchased,...,killAfterHiddenWithAlly,killedChampTookFullTeamDamageSurvived,knockEnemyIntoTeamAndKill,pickKillWithAlly,saveAllyFromDeath,survivedThreeImmobilizesInFight,tookLargeDamageSurvived,takedownsFirstXMinutes,killingSprees_y,playedChampSelectPosition
0,0,5,0,0,9886,12,126,Jayce,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,13,0,0,9628,12,64,LeeSin,0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,4,0,3,11620,14,4,TwistedFate,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,6,0,1,9349,12,145,Kaisa,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,12,0,0,8559,11,526,Rell,0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7215,5,3,0,1,9522,12,147,Seraphine,0,2,...,1.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,NaN,1.0
7216,6,4,0,0,8160,11,80,Pantheon,0,1,...,0.0,0.0,0.0,6.0,0.0,0.0,0.0,4.0,NaN,1.0
7217,7,2,0,0,10103,13,84,Akali,0,1,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,1.0,1.0
7218,8,2,0,3,7777,11,895,Nilah,0,3,...,3.0,0.0,2.0,8.0,0.0,0.0,0.0,6.0,2.0,1.0
7219,9,6,0,1,5047,9,53,Blitzcrank,0,5,...,2.0,0.0,1.0,6.0,0.0,0.0,0.0,4.0,NaN,1.0

In [20]:
partida01.columns

Index(['teamId', 'spell1Id', 'spell2Id', 'championId', 'profileIconId',
       'summonerName', 'bot', 'summonerId', 'gameCustomizationObjects',
       'perks.perkIds', 'perks.perkStyle', 'perks.perkSubStyle'],
      dtype='object')

In [22]:
hist = ut.historial_partidas('GC Darius Brando')
hist

Se finalizo el proceso de transformacion para GC Darius Brando.

['LA2_1046969177',
 'LA2_1047026520',
 'LA2_1047190809',
 'LA2_1047196252',
 'LA2_1047201490',
 'LA2_1047623638',
 'LA2_1047708088',
 'LA2_1047912604',
 'LA2_1047927431',
 'LA2_1047948109',
 'LA2_1047965835',
 'LA2_1048353870',
 'LA2_1048949393',
 'LA2_1048967527',
 'LA2_1048992227',
 'LA2_1050301354',
 'LA2_1050336929',
 'LA2_1050343664',
 'LA2_1050844757',
 'LA2_1053653664',
 'LA2_1053659005',
 'LA2_1053725241',
 'LA2_1054150105',
 'LA2_1056048544',
 'LA2_1058018204',
 'LA2_1061817621',
 'LA2_1061872965',
 'LA2_1063042999',
 'LA2_1063092673',
 'LA2_1063110244',
 'LA2_1063173366',
 'LA2_1063178027',
 'LA2_1064378802',
 'LA2_1064403058',
 'LA2_1064435937',
 'LA2_1064489380',
 'LA2_1064491277',
 'LA2_1064512698',
 'LA2_1065780594',
 'LA2_1065783848',
 'LA2_1065816259',
 'LA2_1065850597',
 'LA2_1065915132',
 'LA2_1065917007',
 'LA2_1065928521',
 'LA2_1065951346',
 'LA2_1066000064',
 'LA2_1066087993',
 'LA2_1066091968',
 'LA2_1066428959',
 'LA2_1066434611',
 'LA2_1066452675',
 'LA2_1066496180',
 'LA2_1066532725',
 'LA2_1066555126',
 'LA2_1066915927',
 'LA2_1066941421',
 'LA2_1067000200',
 'LA2_1067239803',
 'LA2_1067350363',
 'LA2_1067783759',
 'LA2_1067787675',
 'LA2_1068108571',
 'LA2_1068117312',
 'LA2_1068191128',
 'LA2_1068194944',
 'LA2_1068480389',
 'LA2_1068584736',
 'LA2_1068590745',
 'LA2_1068706136',
 'LA2_1068813844',
 'LA2_1068828513',
 'LA2_1068905075',
 'LA2_1069010552',
 'LA2_1069023610',
 'LA2_1069221620',
 'LA2_1069234198',
 'LA2_1069315822',
 'LA2_1069350857',
 'LA2_1069787997',
 'LA2_1070205644',
 'LA2_1070261846',
 'LA2_1070643478',
 'LA2_1070690086',
 'LA2_1072779448',
 'LA2_1073139520',
 'LA2_1073587297',
 'LA2_1075162070',
 'LA2_1075196377',
 'LA2_1075222880',
 'LA2_1075518849',
 'LA2_1075570096',
 'LA2_1075590325',
 'LA2_1075624867',
 'LA2_1075967717',
 'LA2_1075985540',
 'LA2_1076001170',
 'LA2_1076043569',
 'LA2_1076057684',
 'LA2_1076296002',
 'LA2_1076311942',
 'LA2_1076380566',
 'LA2_1076496077',
 'LA2_1076499993',
 'LA2_1076750337',
 'LA2_1076763161',
 'LA2_1076826989',
 'LA2_1076831311',
 'LA2_1076958554',
 'LA2_1076975858',
 'LA2_1077437476',
 'LA2_1077480387',
 'LA2_1077485962',
 'LA2_1077493162',
 'LA2_1077573772',
 'LA2_1077603158',
 'LA2_1077617329',
 'LA2_1077973769',
 'LA2_1077986536',
 'LA2_1078082546',
 'LA2_1078088586',
 'LA2_1078320281',
 'LA2_1078789597',
 'LA2_1078843733',
 'LA2_1078846863',
 'LA2_1079705099',
 'LA2_1079783022',
 'LA2_1079793985',
 'LA2_1079943673',
 'LA2_1080324900',
 'LA2_1080358128',
 'LA2_1080364860',
 'LA2_1080679340',
 'LA2_1080779557',
 'LA2_1080800583',
 'LA2_1080988494',
 'LA2_1081059811',
 'LA2_1081196539',
 'LA2_1081211443',
 'LA2_1081219793',
 'LA2_1081537099',
 'LA2_1081950967',
 'LA2_1081956399',
 'LA2_1081962133',
 'LA2_1082647907',
 'LA2_1082680723',
 'LA2_1082704466',
 'LA2_1082731587',
 'LA2_1083052549',
 'LA2_1083065315',
 'LA2_1083081088',
 'LA2_1083085733',
 'LA2_1083130483',
 'LA2_1083288711',
 'LA2_1083321986',
 'LA2_1083325268',
 'LA2_1083369608',
 'LA2_1083727832',
 'LA2_1083803317',
 'LA2_1084140521',
 'LA2_1084173815',
 'LA2_1084177281',
 'LA2_1084389194',
 'LA2_1084474687',
 'LA2_1084478150',
 'LA2_1084776148',
 'LA2_1085546379',
 'LA2_1085770162',
 'LA2_1085811828',
 'LA2_1085825283',
 'LA2_1086209083',
 'LA2_1086214402',
 'LA2_1086541122',
 'LA2_1086545339',
 'LA2_1086598352',
 'LA2_1086603603',
 'LA2_1086631915',
 'LA2_1086871301',
 'LA2_1087010768',
 'LA2_1087034662',
 'LA2_1087080742',
 'LA2_1087289344',
 'LA2_1087329660',
 'LA2_1087354905',
 'LA2_1087373231',
 'LA2_1087443699',
 'LA2_1087448678',
 'LA2_1087530952',
 'LA2_1087534341',
 'LA2_1087578015',
 'LA2_1087599102',
 'LA2_1087620791',
 'LA2_1087665338',
 'LA2_1087700290',
 'LA2_1087704780',
 'LA2_1088074429',
 'LA2_1088208993',
 'LA2_1088231849',
 'LA2_1088246463',
 'LA2_1088287229',
 'LA2_1088292364',
 'LA2_1088333044',
 'LA2_1088574549',
 'LA2_1088588573',
 'LA2_1088637107',
 'LA2_1088983345',
 'LA2_1089024127',
 'LA2_1089096842',
 'LA2_1089119607',
 'LA2_1089367666',
 'LA2_1089368731',
 'LA2_1089409376',
 'LA2_1089454560',
 'LA2_1089461223',
 'LA2_1089830420',
 'LA2_1089861874',
 'LA2_1089866178',
 'LA2_1089903245',
 'LA2_1090129778',
 'LA2_1090187090',
 'LA2_1090212284',
 'LA2_1090236530',
 'LA2_1090261280',
 'LA2_1090445849',
 'LA2_1090734433',
 'LA2_1090766033',
 'LA2_1090787914',
 'LA2_1090810123',
 'LA2_1090940945',
 'LA2_1090943971',
 'LA2_1090948426',
 'LA2_1091150919',
 'LA2_1091170692',
 'LA2_1091174457',
 'LA2_1092306899',
 'LA2_1092333275',
 'LA2_1092339122',
 'LA2_1092382524',
 'LA2_1092386481',
 'LA2_1093167571',
 'LA2_1093173179',
 'LA2_1093350280',
 'LA2_1093573916',
 'LA2_1093599622',
 'LA2_1093726151',
 'LA2_1093740320',
 'LA2_1093742531',
 'LA2_1093886996',
 'LA2_1093950412',
 'LA2_1094209553',
 'LA2_1094236137',
 'LA2_1094249708',
 'LA2_1094272317',
 'LA2_1094310210',
 'LA2_1094313315',
 'LA2_1094548942',
 'LA2_1094553402',
 'LA2_1094575944',
 'LA2_1094616361',
 'LA2_1094970925',
 'LA2_1095035747',
 'LA2_1095041402',
 'LA2_1095273870',
 'LA2_1095307322',
 'LA2_1095351364',
 'LA2_1095364502',
 'LA2_1095895386',
 'LA2_1095902027',
 'LA2_1095927340',
 'LA2_1095937517',
 'LA2_1095961360',
 'LA2_1096038891',
 'LA2_1096052356',
 'LA2_1096065551',
 'LA2_1096077913',
 'LA2_1096277179',
 'LA2_1096408639',
 'LA2_1096463648',
 'LA2_1096678499',
 'LA2_1096703080',
 'LA2_1096745371',
 'LA2_1096759667',
 'LA2_1096793117',
 'LA2_1097080649',
 'LA2_1097093377',
 'LA2_1097096863',
 'LA2_1097127316',
 'LA2_1097139732',
 'LA2_1097154564',
 'LA2_1097159765',
 'LA2_1097401586',
 'LA2_1097451068',
 'LA2_1097463833',
 'LA2_1097468039',
 'LA2_1097769953',
 'LA2_1097776319',
 'LA2_1097813693',
 'LA2_1097817753',
 'LA2_1097841065',
 'LA2_1097867984',
 'LA2_1097932035',
 'LA2_1098547707',
 'LA2_1098578740',
 'LA2_1098580997',
 'LA2_1098604123',
 'LA2_1098613474',
 'LA2_1098888502',
 'LA2_1099176984',
 'LA2_1099240705',
 'LA2_1099283056',
 'LA2_1099553802',
 'LA2_1099593154',
 'LA2_1099597034',
 'LA2_1099763767',
 'LA2_1099956126',
 'LA2_1100000891',
 'LA2_1100204668',
 'LA2_1100216376',
 'LA2_1100240116',
 'LA2_1100253155',
 'LA2_1100320854',
 'LA2_1100335134',
 'LA2_1100337876',
 'LA2_1100394111',
 'LA2_1100438879',
 'LA2_1100464605',
 'LA2_1100473990',
 'LA2_1100481285',
 'LA2_1100505480',
 'LA2_1100968727',
 'LA2_1100971771',
 'LA2_1100975836',
 'LA2_1101261263',
 'LA2_1101266102',
 'LA2_1101710848',
 'LA2_1102043649',
 'LA2_1102151939',
 'LA2_1102158433',
 'LA2_1102390645',
 'LA2_1102396834',
 'LA2_1102400744',
 'LA2_1102452477',
 'LA2_1102456475',
 'LA2_1103490584',
 'LA2_1103500214',
 'LA2_1103534613',
 'LA2_1104476961',
 'LA2_1104497796',
 'LA2_1104502240',
 'LA2_1108254689',
 'LA2_1108301018',
 'LA2_1109020464',
 'LA2_1109100150',
 'LA2_1109133749',
 'LA2_1109186472',
 'LA2_1109217261',
 'LA2_1109311755',
 'LA2_1109380761',
 'LA2_1109496515',
 'LA2_1109531391',
 'LA2_1109588798',
 'LA2_1109590073',
 'LA2_1109594505',
 'LA2_1109865719',
 'LA2_1109870462',
 'LA2_1110412807',
 'LA2_1110426515',
 'LA2_1112551595',
 'LA2_1112996642',
 'LA2_1113011360',
 'LA2_1114601286',
 'LA2_1114604647',
 'LA2_1114630827',
 'LA2_1114643378',
 'LA2_1115315351',
 'LA2_1115341098',
 'LA2_1115678331',
 'LA2_1115753739',
 'LA2_1116526557',
 'LA2_1116600017',
 'LA2_1117858109',
 'LA2_1117910288',
 'LA2_1118050612',
 'LA2_1118068186',
 'LA2_1118073929',
 'LA2_1118102308',
 'LA2_1118139478',
 'LA2_1118163836',
 'LA2_1118509201',
 'LA2_1118514138',
 'LA2_1119436905',
 'LA2_1119471008',
 'LA2_1119811936',
 'LA2_1123208999',
 'LA2_1123242704',
 'LA2_1123518340',
 'LA2_1123561297',
 'LA2_1124751677',
 'LA2_1124775013',
 'LA2_1125174252',
 'LA2_1125776864',
 'LA2_1125792528',
 'LA2_1126045319',
 'LA2_1126046541',
 'LA2_1126050141',
 'LA2_1126059123',
 'LA2_1126122801',
 'LA2_1126252623',
 'LA2_1126479812',
 'LA2_1127039665',
 'LA2_1127055563',
 'LA2_1127080562',
 'LA2_1128726843',
 'LA2_1128797314',
 'LA2_1129054686',
 'LA2_1129059807',
 'LA2_1129080780',
 'LA2_1129132343',
 'LA2_1129194641',
 'LA2_1129688996',
 'LA2_1129711497',
 'LA2_1130039262',
 'LA2_1130064568',
 'LA2_1130069580',
 'LA2_1130799569',
 'LA2_1130853717',
 'LA2_1130890436',
 'LA2_1131154298',
 'LA2_1131196199',
 'LA2_1131203197',
 'LA2_1131287257',
 'LA2_1131311669',
 'LA2_1131888715',
 'LA2_1131911781',
 'LA2_1131920811',
 'LA2_1131966691',
 'LA2_1131980889',
 'LA2_1131984786',
 'LA2_1132032777',
 'LA2_1132046327',
 'LA2_1132095361',
 'LA2_1132844498',
 'LA2_1132876774',
 'LA2_1132901377',
 'LA2_1132937397',
 'LA2_1132981952',
 'LA2_1133329883',
 'LA2_1133363905',
 'LA2_1133392350',
 'LA2_1134350053',
 'LA2_1134388490',
 'LA2_1134410341',
 'LA2_1134429933',
 'LA2_1134444933',
 'LA2_1134556538',
 'LA2_1134567284',
 'LA2_1134775821',
 'LA2_1134930961',
 'LA2_1135142381',
 'LA2_1135180535',
 'LA2_1135186202',
 'LA2_1135192049',
 'LA2_1135202530',
 'LA2_1135976950',
 'LA2_1136022439',
 'LA2_1136177059',
 'LA2_1136691160',
 'LA2_1138506836',
 'LA2_1138556056',
 'LA2_1140394943',
 'LA2_1140911710',
 'LA2_1140916234',
 'LA2_1140951337',
 'LA2_1141291235',
 'LA2_1141296281',
 'LA2_1141523454',
 'LA2_1141562674',
 'LA2_1141565341',
 'LA2_1141635452',
 'LA2_1141648741',
 'LA2_1141660822',
 'LA2_1142526948',
 'LA2_1142581236',
 'LA2_1143776896',
 'LA2_1143791264',
 'LA2_1144963347',
 'LA2_1144966746',
 'LA2_1146609464',
 'LA2_1146625766',
 'LA2_1147321390',
 'LA2_1147327180',
 'LA2_1147381706',
 'LA2_1148214641',
 'LA2_1149789044',
 'LA2_1149837787',
 'LA2_1149841056',
 'LA2_1150122010',
 'LA2_1150134812',
 'LA2_1150147738',
 'LA2_1150297277',
 'LA2_1150326116',
 'LA2_1150342252',
 'LA2_1150541212',
 'LA2_1150700166',
 'LA2_1150829267',
 'LA2_1151047687',
 'LA2_1151104783',
 'LA2_1151108824',
 'LA2_1151804442',
 'LA2_1152952218',
 'LA2_1171976381',
 'LA2_1172020463',
 'LA2_1172131441',
 'LA2_1179065633',
 'LA2_1181374855',
 'LA2_1183051479',
 'LA2_1184747144',
 'LA2_1187523589',
 'LA2_1188493121',
 'LA2_1189094589',
 'LA2_1189799419',
 'LA2_1189813832',
 'LA2_1190478422',
 'LA2_1190504612',
 'LA2_1191156282',
 'LA2_1191606811',
 'LA2_1191709720',
 'LA2_1191824212',
 'LA2_1192117347',
 'LA2_1192122014',
 'LA2_1194571181',
 'LA2_1196906065',
 'LA2_1197276250',
 'LA2_1197292727',
 'LA2_1197639021',
 'LA2_1197693547',
 'LA2_1198067887',
 'LA2_1198112267',
 'LA2_1198412615',
 'LA2_1198881796',
 'LA2_1198885018',
 'LA2_1198910030',
 'LA2_1199044291',
 'LA2_1200215970',
 'LA2_1200230807',
 'LA2_1201303193',
 'LA2_1201368750',
 'LA2_1201413737',
 'LA2_1201668030',
 'LA2_1201683535',
 'LA2_1201908274',
 'LA2_1201986246',
 'LA2_1201992289',
 'LA2_1202400771',
 'LA2_1202656512',
 'LA2_1203087207',
 'LA2_1203436311',
 'LA2_1203658789',
 'LA2_1203840264',
 'LA2_1203859194',
 'LA2_1203864147',
 'LA2_1203883796',
 'LA2_1206758191',
 'LA2_1206783862',
 'LA2_1216102415',
 'LA2_1216108831',
 'LA2_1216153522',
 'LA2_1220726392',
 'LA2_1225142804',
 'LA2_1236434485',
 'LA2_1236458179',
 'LA2_1238550979',
 'LA2_1238565916',
 'LA2_1238617006',
 'LA2_1238634174',
 'LA2_1238655358',
 'LA2_1238748102',
 'LA2_1238753026',
 'LA2_1238758093',
 'LA2_1238763954',
 'LA2_1238778374',
 'LA2_1238908295',
 'LA2_1238928421',
 'LA2_1239379588',
 'LA2_1239392893',
 'LA2_1240657030',
 'LA2_1240671930',
 'LA2_1241383288',
 'LA2_1241396205',
 'LA2_1241406836',
 'LA2_1241410657',
 'LA2_1241459492',
 'LA2_1241688981',
 'LA2_1241995688',
 'LA2_1242010655',
 'LA2_1242274044',
 'LA2_1242277679',
 'LA2_1242301383',
 'LA2_1242581968',
 'LA2_1242791427',
 'LA2_1242975505',
 'LA2_1243123715',
 'LA2_1243141809',
 'LA2_1243181663',
 'LA2_1243200076',
 'LA2_1243224185',
 'LA2_1243274700',
 'LA2_1243292129',
 'LA2_1243329723',
 'LA2_1243380034',
 'LA2_1243406581',
 'LA2_1243438546',
 'LA2_1243677469',
 'LA2_1243689838',
 'LA2_1243782444',
 'LA2_1243949741',
 'LA2_1243960912',
 'LA2_1243977256',
 'LA2_1243980720',
 'LA2_1244032745',
 'LA2_1244249579',
 'LA2_1244290415',
 'LA2_1244310702',
 'LA2_1244353898',
 'LA2_1244837533',
 'LA2_1244946085',
 'LA2_1246644138',
 'LA2_1246660099',
 'LA2_1246677892',
 'LA2_1246690860',
 'LA2_1246763835',
 'LA2_1247371336',
 'LA2_1247380627',
 'LA2_1247392693',
 'LA2_1247400313',
 'LA2_1247412700',
 'LA2_1247434279',
 'LA2_1247450534',
 'LA2_1247468248',
 'LA2_1247482505',
 'LA2_1247677861',
 'LA2_1247709954',
 'LA2_1247712740',
 'LA2_1247721957',
 'LA2_1247738614',
 'LA2_1248173296',
 'LA2_1248228006',
 'LA2_1248526314',
 'LA2_1248536240',
 'LA2_1248546711',
 'LA2_1248561121',
 'LA2_1248586884',
 'LA2_1248837269',
 'LA2_1248847937',
 'LA2_1248950175',
 'LA2_1249190172',
 'LA2_1249272179',
 'LA2_1250167225',
 'LA2_1250215592',
 'LA2_1250235546',
 'LA2_1252711899',
 'LA2_1252731098',
 'LA2_1255020096',
 'LA2_1257865531',
 'LA2_1257878161',
 'LA2_1259107902',
 'LA2_1261421029',
 'LA2_1261431239',
 'LA2_1261447928',
 'LA2_1261878505',
 'LA2_1261890476',
 'LA2_1271203174',
 'LA2_1271212987',
 'LA2_1271229810',
 'LA2_1271257370',
 'LA2_1271268182',
 'LA2_1271281142',
 'LA2_1271310422',
 'LA2_1271366485',
 'LA2_1271391759',
 'LA2_1271412484',
 'LA2_1271427607',
 'LA2_1271445335',
 'LA2_1271608547',
 'LA2_1271628849',
 'LA2_1271660886',
 'LA2_1271683235',
 'LA2_1271699708',
 'LA2_1271984508',
 'LA2_1272000385',
 'LA2_1272021026',
 'LA2_1272281342',
 'LA2_1272621191',
 'LA2_1272637638',
 'LA2_1272645500',
 'LA2_1272661400',
 'LA2_1272678171',
 'LA2_1272745066',
 'LA2_1272751699',
 'LA2_1272783507',
 'LA2_1272795685',
 'LA2_1272852994',
 'LA2_1272864559',
 'LA2_1272880447',
 'LA2_1272900563',
 'LA2_1272957217',
 'LA2_1272968657',
 'LA2_1272988224',
 'LA2_1273056562',
 'LA2_1273061803',
 'LA2_1273116681',
 'LA2_1273127890',
 'LA2_1273183139',
 'LA2_1273198367',
 'LA2_1273201527',
 'LA2_1273809198',
 'LA2_1274158238',
 'LA2_1274452208',
 'LA2_1274459283',
 'LA2_1274480316',
 'LA2_1275391469',
 'LA2_1278404791',
 'LA2_1279622574',
 'LA2_1279649476',
 'LA2_1279943439',
 'LA2_1280193838',
 'LA2_1280218098',
 'LA2_1280402608',
 'LA2_1280405359',
 'LA2_1280425119',
 'LA2_1280512179',
 'LA2_1282192998',
 'LA2_1282502215',
 'LA2_1283943073',
 'LA2_1283964803',
 'LA2_1283984638',
 'LA2_1284084738',
 'LA2_1284103652',
 'LA2_1287694934',
 'LA2_1287710969',
 'LA2_1287733893',
 'LA2_1287756142',
 'LA2_1287768248',
 'LA2_1288939771',
 'LA2_1296312380',
 'LA2_1296329216',
 'LA2_1296341531',
 'LA2_1296348859',
 'LA2_1296355726',
 'LA2_1297819792',
 'LA2_1298158379',
 'LA2_1298179200',
 'LA2_1298549121',
 'LA2_1298645507',
 'LA2_1298654289',
 'LA2_1298885067',
 'LA2_1298951920',
 'LA2_1299101917',
 'LA2_1299107661',
 'LA2_1299120225',
 'LA2_1299133383',
 'LA2_1299143811',
 'LA2_1299609750',
 'LA2_1299638158',
 'LA2_1299912811',
 'LA2_1299933308',
 'LA2_1300529241',
 'LA2_1300545812',
 'LA2_1300590835',
 'LA2_1300611866',
 'LA2_1300802825',
 'LA2_1300951069',
 'LA2_1300961540',
 'LA2_1300979494',
 'LA2_1301505119',
 'LA2_1301646504',
 'LA2_1301679752',
 'LA2_1301881670']

In [23]:
ut.detalle_partidas('LA2_1301881670')

Se finalizo el proceso para la partida LA2_1301881670

,allInPings,assistMePings,assists,baitPings,baronKills,basicPings,bountyLevel,champExperience,champLevel,championId,...,turretTakedowns,turretsLost,unrealKills,visionClearedPings,visionScore,visionWardsBoughtInGame,wardsKilled,wardsPlaced,win,id_game
0,0,1,19,0,0,0,0,17633,17,8,...,5,3,0,0,17,0,2,8,True,LA2_1301881670
1,2,0,9,0,0,0,0,14313,15,35,...,0,3,0,0,22,0,2,4,True,LA2_1301881670
2,0,0,13,0,1,0,17,20820,18,136,...,5,3,0,0,13,0,1,7,True,LA2_1301881670
3,0,2,13,0,0,0,0,16411,16,145,...,4,3,0,1,27,0,5,10,True,LA2_1301881670
4,1,6,30,0,0,0,0,13938,15,53,...,2,3,0,1,67,1,4,29,True,LA2_1301881670
5,0,1,14,0,0,0,0,14880,16,516,...,1,8,0,0,20,1,1,8,False,LA2_1301881670
6,0,12,5,0,0,0,0,14521,15,234,...,1,8,0,0,30,5,2,5,False,LA2_1301881670
7,0,5,7,0,0,0,0,14922,16,39,...,1,8,0,0,33,6,3,9,False,LA2_1301881670
8,0,0,8,0,0,0,0,13955,15,222,...,1,8,0,0,18,1,0,12,False,LA2_1301881670
9,0,1,11,0,0,0,2,13807,15,43,...,1,8,0,0,41,0,3,22,False,LA2_1301881670

In [27]:
ut.detalle_challenge_partida(['LA2_1301881670'])

,12AssistStreakCount,abilityUses,acesBefore15Minutes,alliedJungleMonsterKills,baronBuffGoldAdvantageOverThreshold,baronTakedowns,blastConeOppositeOpponentCount,bountyGold,buffsStolen,completeSupportQuestInTime,...,junglerKillsEarlyJungle,killsOnLanersEarlyJungleAsJungler,fastestLegendary,highestWardKills,soloTurretsLategame,controlWardTimeCoverageInRiverOrEnemyHalf,highestCrowdControlScore,fasterSupportQuestCompletion,id_game,summonerId
0,0,456,0,3,1.0,0,0,525,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LA2_1301881670,OFRslar8Gddqq-dmZSxI5KSB4mnR1TccZ-qIMEwFjckDmdg
1,0,216,0,51,1.0,1,0,150,1,0,...,0.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,LA2_1301881670,K2twAA5gA-gMXY4YVq0szKaX-er9Hlhz8sitMu4lzN00Qw
2,0,208,0,0,1.0,1,0,375,0,0,...,NaN,NaN,1635.029845,NaN,NaN,NaN,NaN,NaN,LA2_1301881670,UuoNbnfTvcLE92oDoFsSgpL4MRt8EEUiIyOTUHdTKkCrIj...
3,0,204,0,1,1.0,1,0,150,1,0,...,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,LA2_1301881670,xFSyM3b5kdX6naAbEIT1ZpAU6yWSZVxar74uwwMxYZiXSQ
4,2,131,0,0,1.0,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,0.813772,1.0,NaN,LA2_1301881670,FVQH2Ku1IsMqpNtDkhjLAF7esiH2UDOGdACSXgWJEfD5GNU
5,0,195,0,0,NaN,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LA2_1301881670,03w6OhOJXa9JtJTgKcbLn_uay2pWIVDy3ooihK6gCBkGTA
6,0,373,0,72,NaN,0,0,875,2,0,...,0.0,4.0,NaN,NaN,NaN,0.825422,NaN,NaN,LA2_1301881670,he-D1TnFFED6TX3prBP45PZlgCpn2BjLb3mwu7XzyXtgpiE
7,0,363,0,2,NaN,0,0,450,1,0,...,NaN,NaN,NaN,NaN,NaN,0.877191,NaN,NaN,LA2_1301881670,NyTz6f8K7q9c4jhUAmBgLruSx6b6zx1Z1B1Fqq6hTCrFqA
8,0,155,0,9,NaN,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,0.811522,NaN,NaN,LA2_1301881670,oB4cUXKmbdGq2skGPd4Fy4ZtbfSjfv_v32Xo7ToVKeE1yW...
9,0,230,0,0,NaN,0,0,150,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,LA2_1301881670,CZMrNyx2yMPE4A2i478sFd8HxsAuG5IJA7rpx6XXegxM

<h3 style="font-size:20px; 
           color:orangered;
           text-align:left">
    Debemos modificar la funcion de debajo para que dentro de los datos que nos traiga este incluido los datos de los Perks que uso cada uno de los jugadores.</h3>

In [ ]:
def detalle_partidas(id_partida:str)->pd.DataFrame:
    
    # Establecemos una coneccion con la API para extraer los datos
    url = f"https://americas.api.riotgames.com/lol/match/v5/matches/{id_partida}?api_key={key_admin}"
    
    try:
        # Establecemos la coneccion con la api
        response = requests.get(url)
        if response.status_code != 200:
            print(f"Error al obtener los datos de la partida {partida}.")
        else:
            None

        # Convertimos el json
        json_info = json.loads(response.text)

        # Comenzamos a transformar el json en un df
        match_information = pd.DataFrame(json_info['info']['participants'])
        
        # Reiniciamos el índice para evitar índices duplicados
        match_information.reset_index(drop=True, inplace=True)

        # Nos fijamos si existe la columna challenges
        if 'challenges'in match_information.columns: 

            # Desglozamos la columna que quedo como un diccionario
            match_information.drop(['challenges'], axis=1, inplace = True)
            
        else:
            None

        # Eliminamos las columnas que no nos sirven
        match_information.drop(['perks'], axis=1, inplace = True)

        # Establecemos una columna con el nombre del id de la partida
        match_information['id_game'] = id_partida
        print(f"Se finalizo el proceso para la partida {id_partida}")

        return match_information
    
    except Exception as e:
        print(f"Error al obtener los datos de la partida {id_partida}: {e}")
        return pd.DataFrame()

In [6]:
# Establecemos una coneccion con la API para extraer los datos
url = f"https://americas.api.riotgames.com/lol/match/v5/matches/LA2_1301881670?api_key={key_admin}"

# Establecemos la coneccion con la api
response = requests.get(url)
if response.status_code != 200:
    print(f"Error al obtener los datos de la partida LA2_1301881670.")
else:
    None

# Convertimos el json
json_info = json.loads(response.text)

# Comenzamos a transformar el json en un df
match_information = pd.DataFrame(json_info['info']['participants'])

# Reiniciamos el índice para evitar índices duplicados
match_information.reset_index(drop=True, inplace=True)

# Nos fijamos si existe la columna challenges
if 'challenges'in match_information.columns: 

    # Desglozamos la columna que quedo como un diccionario
    match_information.drop(['challenges'], axis=1, inplace = True)
    
else:
    None

# Establecemos una columna con el nombre del id de la partida
match_information['id_game'] = 'LA2_1301881670'
print(f"Se finalizo el proceso para la partida LA2_1301881670")

Se finalizo el proceso para la partida LA2_1301881670

In [12]:
## Vamos a ir desglozando perks

# perks
# pd.json_normalize(match_information['perks'])
#  tenemos el estilo, perk defensivo, el felxible y el ofensivo

# 2 nivel de perks
# pd.json_normalize(pd.json_normalize(match_information['perks'])['styles'])
# Tenemos el estilo primario y el sub estilo, son valores 1 o 0

# 3 nivel de perks
# pd.json_normalize(pd.json_normalize(pd.json_normalize(match_information['perks'])['styles'])[1])
# Tenemos las seleciones, y el estilo de las mismas

# 4 nivel de perks
# pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(match_information['perks'])['styles'])[1])['selections'])
# Tenemos los perks primarios y secundartios con sus var, tenemos un 1 oo un 0 en este caso

# 5 nivel de perks
pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(match_information['perks'])['styles'])[0])['selections'])[0])
# Tenemos el perk con los datos finales

   perk  var1  var2  var3
0  8230    30     0     0
1  8128  1373    22     0
2  8229  3472     0     0
3  8008    63     7     0
4  8439   771  1453     0
5  8437   920   580     0
6  8010   530     0     0
7  8010   754     0     0
8  8008    54     0     0
9  8128  1438    20     0

# I. Armado de la primera parte

## La formula 1

In [ ]:
# Creamos la funcion para que nos de los datos de la partida en viv
    
def live_match(nombre_jugador:str)->pd.DataFrame:
    
    #definimos algunas variables
    key = key_admin
    region = 'la2'
        
    # Creamos el df para almacenar los datos
    df_match = pd.DataFrame()
    
    # Obtenemos el id del jugador
    id = datos_invocador([nombre_jugador])['id'][0]
    print(f'El id del jugador es: {id}')
    
    # Conexion a la API
    url = f'https://{region}.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/{id}?api_key={key_admin}'
    response = requests.get(url)
    if response.status_code != 200:
        print(f'Error al obtener datos de: {nombre_jugador}')
        return None
    
    # Lo transformamos en texto 
    texto = response.text
    
    # Lo transformamos en JSON y normalziamos con pd
    json_info = json.loads(texto)
    df_match = pd.json_normalize(json_info)
    
    print(f'Se finalizo el proceso para la partida de {nombre_jugador}')
    
        # Creamos el df vacio
    detalle_partida = pd.DataFrame()

    # Creamos el bucle para normalizar cada JSON    
    for i in range(0,10,1):
        
        # Normalizamos cada jugador
        player_normalize = pd.json_normalize(pd.json_normalize(df_match['participants'])[i])
        
        # Guardamos los datos
        detalle_partida = pd.concat([detalle_partida, player_normalize])
        
    ## Comenzamos con la limpieza de las columnas
    colstodrop = ['summonerName', 'profilelIconId', 'bot', 'gameCustomizationObjects']
    
    # Eliminamos las columnas que no empleamos
    detalle_partida.drop(columns=colstodrop)
    
    # 
    
    return incognita

In [8]:
partida01['perks.perkIds']

0    [8229, 8226, 8210, 8237, 8126, 8106, 5008, 500...
0    [8010, 9111, 9104, 8299, 8473, 8451, 5005, 500...
0    [8112, 8139, 8138, 8135, 8226, 8237, 5005, 500...
0    [8369, 8304, 8321, 8347, 8143, 8135, 5008, 500...
0    [8005, 8009, 9103, 8014, 8345, 8304, 5005, 500...
0    [8229, 8226, 8210, 8237, 8345, 8347, 5008, 500...
0    [8439, 8401, 8473, 8242, 8345, 8347, 5007, 500...
0    [8230, 8226, 8210, 8236, 8009, 8014, 5005, 500...
0    [8008, 9111, 9104, 8014, 8126, 8106, 5005, 500...
0    [8437, 8446, 8473, 8451, 8126, 8106, 5005, 500...
Name: perks.perkIds, dtype: object

In [16]:
partida01.head()

,teamId,spell1Id,spell2Id,championId,profileIconId,summonerName,bot,summonerId,gameCustomizationObjects,perks.perkIds,perks.perkStyle,perks.perkSubStyle
0,100,4,14,99,5736,Foortune,False,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM,[],"[8229, 8226, 8210, 8237, 8126, 8106, 5008, 500...",8200,8100
0,100,4,12,150,4864,M1KE TYS0N,False,FP95A4NcwZsbHYKATDFJpAMv8wzOpyxHxnfkadid94XNeCQ,[],"[8010, 9111, 9104, 8299, 8473, 8451, 5005, 500...",8000,8400
0,100,4,14,518,5434,AntonyKiller77,False,VxqE0JuZi21SybY9oHea7IRvliueUMhz4sKn5cTZeCDDS2...,[],"[8112, 8139, 8138, 8135, 8226, 8237, 5005, 500...",8100,8200
0,100,4,11,121,5755,PermAcànc3r,False,nU5_o77OIGTyHeMPNLC2mQ1L3khgtloykhzXa4HAuGHwuf...,[],"[8369, 8304, 8321, 8347, 8143, 8135, 5008, 500...",8300,8100
0,100,7,4,81,11,peneriko123,False,8s9RcWQHEFrV4BjRNloqMVa8I5LCSGknzuzTuCM_cp64YS...,[],"[8005, 8009, 9103, 8014, 8345, 8304, 5005, 500...",8000,8300

In [15]:
def champions_mastery(nombres_invocador:list)->pd.DataFrame():
       
    # Definimos algunas variables
    key = key_admin
    region = 'LA2'
    
    # Creamos un dataframe vacio
    df_summoner_mastery = pd.DataFrame()
    
    # Tenemos que obtener el id del dataframe obtenido anteriormente en base al nombre que ingresemos
    summoners_id =  nombres_invocador
    
    # Creamos un bucle for para que tome todos los nombre que indiquemos
    for summoner_id in summoners_id:
    
        # Nos conectamos a la api para obtener los datos
        api_for_mastery = f'https://{region}.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-summoner/{summoner_id}?api_key={key}'

        response = requests.get(api_for_mastery)
        if response.status_code != 200:
            print(f"Error: no se pudo obtener la maestría de campeones del invocador {summoner_id}.")
            return None

        # Lo transformamos en un texto
        texto = response.text

        # Lo transformamos en un JSON y lo normalizamos en un pd.df
        json_info = json.loads(texto)
        mastery_information = pd.json_normalize(json_info)

        # Almacenamos los datos
        df_summoner_mastery = pd.concat([df_summoner_mastery, mastery_information], ignore_index=True)

        print(f'Se finalizo el proceso de transformacion para {summoner_id}.')
        
    # Eliminaremos las columnas que no sean necesarias
    colstodrop = ['puuid', 'lastPlayTime', 'championPointsSinceLastLevel', 'championPointsUntilNextLevel',
                  'chestGranted', 'tokensEarned']
    df_summoner_mastery.drop(columns=colstodrop)
    
    return df_summoner_mastery

champions_mastery(['55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM'])

Se finalizo el proceso de transformacion para 55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM.

,puuid,championId,championLevel,championPoints,lastPlayTime,championPointsSinceLastLevel,championPointsUntilNextLevel,chestGranted,tokensEarned,summonerId
0,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,99,7,293709,1685927577000,272109,0,True,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
1,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,21,7,260589,1685284583000,238989,0,True,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
2,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,25,7,91799,1681902265000,70199,0,True,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
3,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,43,7,91341,1684515780000,69741,0,True,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
4,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,145,5,80021,1680576909000,58421,0,True,1,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
...,...,...,...,...,...,...,...,...,...,...
141,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,83,1,107,1588043269000,107,1693,False,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
142,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,113,1,106,1568246911000,106,1694,False,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
143,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,114,1,101,1618779909000,101,1699,False,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
144,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,72,1,92,1587511242000,92,1708,False,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM
145,66R8CIvUCknKjQdkU9lCromJDE3UFL6mKA4DVV5MNNFBSg...,150,1,88,1649356533000,88,1712,False,0,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM

In [13]:
partida01.head()

,teamId,spell1Id,spell2Id,championId,profileIconId,summonerName,bot,summonerId,gameCustomizationObjects,perks.perkIds,perks.perkStyle,perks.perkSubStyle
0,100,4,14,99,5736,Foortune,False,55MEpu53V7U8jG3j_umw8AuBPQAGpaj7EA7D75inMfyGxqM,[],"[8229, 8226, 8210, 8237, 8126, 8106, 5008, 500...",8200,8100
0,100,4,12,150,4864,M1KE TYS0N,False,FP95A4NcwZsbHYKATDFJpAMv8wzOpyxHxnfkadid94XNeCQ,[],"[8010, 9111, 9104, 8299, 8473, 8451, 5005, 500...",8000,8400
0,100,4,14,518,5434,AntonyKiller77,False,VxqE0JuZi21SybY9oHea7IRvliueUMhz4sKn5cTZeCDDS2...,[],"[8112, 8139, 8138, 8135, 8226, 8237, 5005, 500...",8100,8200
0,100,4,11,121,5755,PermAcànc3r,False,nU5_o77OIGTyHeMPNLC2mQ1L3khgtloykhzXa4HAuGHwuf...,[],"[8369, 8304, 8321, 8347, 8143, 8135, 5008, 500...",8300,8100
0,100,7,4,81,11,peneriko123,False,8s9RcWQHEFrV4BjRNloqMVa8I5LCSGknzuzTuCM_cp64YS...,[],"[8005, 8009, 9103, 8014, 8345, 8304, 5005, 500...",8000,8300

# creacion del df para entrenar

In [26]:
def detalle_partidas(id_partida:str)->pd.DataFrame:
    
    # Establecemos una coneccion con la API para extraer los datos
    url = f"https://americas.api.riotgames.com/lol/match/v5/matches/{id_partida}?api_key={key_admin}"
    
    try:
        # Establecemos la coneccion con la api
        response = requests.get(url)
        if response.status_code != 200:
            print(f"Error al obtener los datos de la partida {partida}.")
        else:
            None

        # Convertimos el json
        json_info = json.loads(response.text)

        # Comenzamos a transformar el json en un df
        match_information = pd.DataFrame(json_info['info']['participants'])
        
        # Reiniciamos el índice para evitar índices duplicados
        match_information.reset_index(drop=True, inplace=True)

        # Nos fijamos si existe la columna challenges
        if 'challenges'in match_information.columns: 

            # Desglozamos la columna que quedo como un diccionario
            match_information.drop(['challenges'], axis=1, inplace = True)
            
        else:
            None

        # # Eliminamos las columnas que no nos sirven
        # match_information.drop(['perks'], axis=1, inplace = True)

        # Establecemos una columna con el nombre del id de la partida
        match_information['id_game'] = id_partida
        print(f"Se finalizo el proceso para la partida {id_partida}")
        
        # Seleccionamos las columnas que nos queremos quedar
        colstostay = ['summonerId', 'teamId', 'championId', 'perks', 'win']

        return match_information
    
    except Exception as e:
        print(f"Error al obtener los datos de la partida {id_partida}: {e}")
        return pd.DataFrame()
    
detalle_partidas('LA2_1301881670')

Se finalizo el proceso para la partida LA2_1301881670

In [33]:
A['perks']

0    {'statPerks': {'defense': 5001, 'flex': 5008, ...
1    {'statPerks': {'defense': 5002, 'flex': 5008, ...
2    {'statPerks': {'defense': 5002, 'flex': 5008, ...
3    {'statPerks': {'defense': 5002, 'flex': 5008, ...
4    {'statPerks': {'defense': 5001, 'flex': 5002, ...
5    {'statPerks': {'defense': 5003, 'flex': 5003, ...
6    {'statPerks': {'defense': 5003, 'flex': 5008, ...
7    {'statPerks': {'defense': 5003, 'flex': 5008, ...
8    {'statPerks': {'defense': 5002, 'flex': 5008, ...
9    {'statPerks': {'defense': 5002, 'flex': 5008, ...
Name: perks, dtype: object

In [42]:
## Vamos a ir desglozando perks
# perks
pd.json_normalize(A['perks'])[['statPerks.defense', 'statPerks.flex', 'statPerks.offense']]
#  tenemos el estilo, perk defensivo, el felxible y el ofensivo

   statPerks.defense  statPerks.flex  statPerks.offense
0               5001            5008               5007
1               5002            5008               5005
2               5002            5008               5005
3               5002            5008               5005
4               5001            5002               5007
5               5003            5003               5005
6               5003            5008               5005
7               5003            5008               5005
8               5002            5008               5005
9               5002            5008               5008

In [35]:
# 2 nivel de perks
pd.json_normalize(pd.json_normalize(A['perks'])['styles'])
# Tenemos el estilo primario y el sub estilo, son valores 1 o 0

,0,1
0,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
1,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
2,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
3,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
4,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
5,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
6,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
7,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
8,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."
9,"{'description': 'primaryStyle', 'selections': ...","{'description': 'subStyle', 'selections': [{'p..."

In [55]:
# 3 nivel de perks
pd.DataFrame(pd.json_normalize(pd.json_normalize(pd.json_normalize(A['perks'])['styles'])[1])['style'], columns=['subStyle'])

# B = pd.json_normalize(pd.json_normalize(pd.json_normalize(A['perks'])['styles'])[1])[['description','style']]
# B.rename(columns={'style':'subStyle'})
# Tenemos las seleciones, y el estilo de las mismas

Empty DataFrame
Columns: [subStyle]
Index: []

In [44]:
pd.json_normalize(pd.json_normalize(pd.json_normalize(A['perks'])['styles'])[0])[['description', 'style']]

    description  style
0  primaryStyle   8200
1  primaryStyle   8100
2  primaryStyle   8200
3  primaryStyle   8000
4  primaryStyle   8400
5  primaryStyle   8400
6  primaryStyle   8000
7  primaryStyle   8000
8  primaryStyle   8000
9  primaryStyle   8100

In [37]:
# 4 nivel de perks
pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(A['perks'])['styles'])[1])['selections'])
# Tenemos los perks primarios y secundartios con sus var, tenemos un 1 oo un 0 en este caso

,0,1
0,"{'perk': 8347, 'var1': 0, 'var2': 0, 'var3': 0}","{'perk': 8304, 'var1': 10, 'var2': 3, 'var3': 0}"
1,"{'perk': 8014, 'var1': 456, 'var2': 0, 'var3': 0}","{'perk': 9104, 'var1': 10, 'var2': 10, 'var3': 0}"
2,"{'perk': 8304, 'var1': 10, 'var2': 3, 'var3': 0}","{'perk': 8316, 'var1': 2990, 'var2': 0, 'var3'..."
3,"{'perk': 8345, 'var1': 3, 'var2': 0, 'var3': 0}","{'perk': 8304, 'var1': 9, 'var2': 4, 'var3': 5}"
4,"{'perk': 8345, 'var1': 3, 'var2': 0, 'var3': 0}","{'perk': 8347, 'var1': 0, 'var2': 0, 'var3': 0}"
5,"{'perk': 8304, 'var1': 9, 'var2': 0, 'var3': 0}","{'perk': 8345, 'var1': 3, 'var2': 0, 'var3': 0}"
6,"{'perk': 8143, 'var1': 895, 'var2': 0, 'var3': 0}","{'perk': 8135, 'var1': 450, 'var2': 5, 'var3': 0}"
7,"{'perk': 8473, 'var1': 707, 'var2': 0, 'var3': 0}","{'perk': 8242, 'var1': 101, 'var2': 0, 'var3': 0}"
8,"{'perk': 8233, 'var1': 24, 'var2': 30, 'var3': 0}","{'perk': 8236, 'var1': 28, 'var2': 0, 'var3': 0}"
9,"{'perk': 8210, 'var1': 15, 'var2': 0, 'var3': 0}","{'perk': 8236, 'var1': 48, 'var2': 0, 'var3': 0}"

In [38]:
# 5 nivel de perks
pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(pd.json_normalize(A['perks'])['styles'])[0])['selections'])[0])
# Tenemos el perk con los datos finales

   perk  var1  var2  var3
0  8230    30     0     0
1  8128  1373    22     0
2  8229  3472     0     0
3  8008    63     7     0
4  8439   771  1453     0
5  8437   920   580     0
6  8010   530     0     0
7  8010   754     0     0
8  8008    54     0     0
9  8128  1438    20     0